local base_freq = 261.63 -- C4 note

local function calc_sharp(note)
	return note * 2 ^ (1 / 12) -- Sharps are one semitone up
end

local function calc_flat(note)
	return note / 2 ^ (1 / 12) -- Flats are one semitone down
end

local M = {
	C1 = base_freq / 8,
	Cs1 = calc_sharp(base_freq / 8),
	Db1 = calc_flat((base_freq * 9 / 8) / 8),
	D1 = (base_freq * 9 / 8) / 8,
	Ds1 = calc_sharp((base_freq * 9 / 8) / 8),
	Eb1 = calc_flat((base_freq * 5 / 4) / 8),
	E1 = (base_freq * 5 / 4) / 8,
	F1 = (base_freq * 4 / 3) / 8,
	Fs1 = calc_sharp((base_freq * 4 / 3) / 8),
	Gb1 = calc_flat((base_freq * 3 / 2) / 8),
	G1 = (base_freq * 3 / 2) / 8,
	Gs1 = calc_sharp((base_freq * 3 / 2) / 8),
	Ab1 = calc_flat((base_freq * 5 / 3) / 8),
	A1 = (base_freq * 5 / 3) / 8,
	As1 = calc_sharp((base_freq * 5 / 3) / 8),
	Bb1 = calc_flat((base_freq * 15 / 8) / 8),
	B1 = (base_freq * 15 / 8) / 8,
	C2 = base_freq / 4,
	Cs2 = calc_sharp(base_freq / 4),
	Db2 = calc_flat((base_freq * 9 / 8) / 4),
	D2 = (base_freq * 9 / 8) / 4,
	Ds2 = calc_sharp((base_freq * 9 / 8) / 4),
	Eb2 = calc_flat((base_freq * 5 / 4) / 4),
	E2 = (base_freq * 5 / 4) / 4,
	F2 = (base_freq * 4 / 3) / 4,
	Fs2 = calc_sharp((base_freq * 4 / 3) / 4),
	Gb2 = calc_flat((base_freq * 3 / 2) / 4),
	G2 = (base_freq * 3 / 2) / 4,
	Gs2 = calc_sharp((base_freq * 3 / 2) / 4),
	Ab2 = calc_flat((base_freq * 5 / 3) / 4),
	A2 = (base_freq * 5 / 3) / 4,
	As2 = calc_sharp((base_freq * 5 / 3) / 4),
	Bb2 = calc_flat((base_freq * 15 / 8) / 4),
	B2 = (base_freq * 15 / 8) / 4,
	C3 = base_freq / 2,
	Cs3 = calc_sharp(base_freq / 2),
	Db3 = calc_flat((base_freq * 9 / 8) / 2),
	D3 = (base_freq * 9 / 8) / 2,
	Ds3 = calc_sharp((base_freq * 9 / 8) / 2),
	Eb3 = calc_flat((base_freq * 5 / 4) / 2),
	E3 = (base_freq * 5 / 4) / 2,
	F3 = (base_freq * 4 / 3) / 2,
	Fs3 = calc_sharp((base_freq * 4 / 3) / 2),
	Gb3 = calc_flat((base_freq * 3 / 2) / 2),
	G3 = (base_freq * 3 / 2) / 2,
	Gs3 = calc_sharp((base_freq * 3 / 2) / 2),
	Ab3 = calc_flat((base_freq * 5 / 3) / 2),
	A3 = (base_freq * 5 / 3) / 2,
	As3 = calc_sharp((base_freq * 5 / 3) / 2),
	Bb3 = calc_flat((base_freq * 15 / 8) / 2),
	B3 = (base_freq * 15 / 8) / 2,
	C4 = base_freq,
	Cs4 = calc_sharp(base_freq),
	Db4 = calc_flat(base_freq * 9 / 8),
	D4 = base_freq * 9 / 8,
	Ds4 = calc_sharp(base_freq * 9 / 8),
	Eb4 = calc_flat(base_freq * 5 / 4),
	E4 = base_freq * 5 / 4,
	F4 = base_freq * 4 / 3,
	Fs4 = calc_sharp(base_freq * 4 / 3),
	Gb4 = calc_flat(base_freq * 3 / 2),
	G4 = base_freq * 3 / 2,
	Gs4 = calc_sharp(base_freq * 3 / 2),
	Ab4 = calc_flat(base_freq * 5 / 3),
	A4 = base_freq * 5 / 3,
	As4 = calc_sharp(base_freq * 5 / 3),
	Bb4 = calc_flat(base_freq * 15 / 8),
	B4 = base_freq * 15 / 8,
	C5 = base_freq * 2,
	Cs5 = calc_sharp(base_freq * 2),
	Db5 = calc_flat(base_freq * 9 / 4),
	D5 = base_freq * 9 / 4,
	Ds5 = calc_sharp(base_freq * 9 / 4),
	Eb5 = calc_flat(base_freq * 5 / 2),
	E5 = base_freq * 5 / 2,
	F5 = base_freq * 8 / 3,
	Fs5 = calc_sharp(base_freq * 8 / 3),
	Gb5 = calc_flat(base_freq * 3),
	G5 = base_freq * 3,
	Gs5 = calc_sharp(base_freq * 3),
	Ab5 = calc_flat(base_freq * 10 / 3),
	A5 = base_freq * 10 / 3,
	As5 = calc_sharp(base_freq * 10 / 3),
	Bb5 = calc_flat(base_freq * 15 / 4),
	B5 = base_freq * 15 / 4,
	C6 = base_freq * 4,
	Cs6 = calc_sharp(base_freq * 4),
	Db6 = calc_flat(base_freq * 9 / 2),
	D6 = base_freq * 9 / 2,
	Ds6 = calc_sharp(base_freq * 9 / 2),
	Eb6 = calc_flat(base_freq * 5),
	E6 = base_freq * 5,
	F6 = base_freq * 16 / 3,
	Fs6 = calc_sharp(base_freq * 16 / 3),
	Gb6 = calc_flat(base_freq * 6),
	G6 = base_freq * 6,
	Gs6 = calc_sharp(base_freq * 6),
	Ab6 = calc_flat(base_freq * 20 / 3),
	A6 = base_freq * 20 / 3,
	As6 = calc_sharp(base_freq * 20 / 3),
	Bb6 = calc_flat(base_freq * 15 / 2),
	B6 = base_freq * 15 / 2,
	REST = 0,
}

return M
