name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: dylib
          - os: macos-latest
            target: aarch64-apple-darwin
            suffix: dylib
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: so
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            suffix: so
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: dll

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Prepare binary
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/player_one.${{ matrix.suffix }} dist/${{ matrix.target }}.${{ matrix.suffix }}
          else
            cp target/${{ matrix.target }}/release/libplayer_one.${{ matrix.suffix }} dist/${{ matrix.target }}.${{ matrix.suffix }}
          fi

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist/${{ matrix.target }}.${{ matrix.suffix }}

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
