name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload_artifacts: true

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Verify artifacts
        run: |
          if [ -z "$(find . -type f)" ]; then
            echo "No artifacts found!"
            exit 1
          fi

      - name: Generate checksums
        run: |
          find . -type f -not -name "*.sha256" | while read file; do
            sha256sum "$file" > "${file}.sha256"
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
          files: ./**/*
          draft: false
          prerelease: false
          generate_release_notes: true
